CONFIG = {
    #'mode': 'wsgi',
    'working_dir': '/home/box/web', 
    'user': 'www-data',  
    'group': 'www-data',  
    #'python': '/usr/bin/python',
    'args': (
        '--bind=0.0.0.0:8080',
        '--workers=5', 
        #'--graceful-timeout=60',
        '--timeout=60',
        'app.hello',
    ),
}


